language: cpp

compiler:
  - gcc
  - clang

script: cmake

before_install:
  - echo $LANG
  - echo $LC_ALL
  - sudo apt-get update
  - sudo apt-get install -y default-jre default-jdk
  - export JDK_HOME=/usr
  - svn co https://svnsrv.desy.de/public/ilctools/ilcinstall/trunk/ ilcinstall
  - cd ilcinstall
  - sed -i 's#ilcsoft_install_prefix = "/scratch/$USER/ilcsoft"#ilcsoft_install_prefix = "PACKAGES"#' examples/lcfiplus/release-versions.py
  - sed -i "s#ilcsoft.use(ROOT(os.environ\['ROOTSYS'\]))#ilcsoft.install\(ROOT\(ROOT_version\)\)#" examples/lcfiplus/release-scratch.cfg
  - python ilcsoft-install -i examples/lcfiplus/release-scratch.cfg

before_script:
  - travis_retry bundle
  - if [ $TRAVIS_OS_NAME == linux ]; then travis_retry ./configure --llvm-config llvm-config-3.4; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then travis_retry ./configure; fi

os:
  - linux

