sudo: required
dist: trusty

services:
  - docker

# command to install dependencies
install:
  - shopt -s extglob dotglob
  - mkdir LCFIPlus
  - mv !(LCFIPlus) LCFIPlus
  - shopt -u dotglob
  - export LCFIPlusDIR=${PWD}/LCFIPlus
  - cat $LCFIPlusDIR/.travis-ci.d/compile_and_test.sh
  - curl -O https://lcd-data.web.cern.ch/lcd-data/CernVM/cernvm3-docker-latest.tar
  - cat cernvm3-docker-latest.tar | docker import - cernvm

# command to run tests
script:
  - docker run -t -v $LCFIPlusDIR:/LCFIPlus cernvm /init /LCFIPlus/.travis-ci.d/compile_and_test.sh

# Don't send e-mail notifications
notifications:
  email: false
